[project]
name = "object-detection-project"
version = "0.1.0"
description = "Sign Language Object Detection using YOLO"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "from-root>=1.3.0",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "ultralytics>=8.4.143",
]
